from . import student
from . import teacher
from . import fee_structure
from . import query
from . import sale_orderinherit
from . import __invoicing_project_
from . import journal
from . import product_brand
from . import invoicing_xlsx